# Update data in data-raw when changes are made to the data generating functions.
name: update-data
on:
  push:
    paths:
      - 'innovation.R' # Function which generates regional_innovation data. Also depends on functions below:
      - 'sem_input.R'
      - 'knowledge_capability.R'#Function which generates knowledge capability data. Also depends on functions below:
      - 'designs.R'
      - 'patents.R'
      - 'plants.R'
      - 'pow.R'
      - 'utils.R'

jobs:
  update-data:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        env:
          GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          Rscript -e "install.packages(c('remotes', 'dplyr', 'tidyr', 'purrr', 'scales'), type = 'binary')"
          Rscript -e "remotes::install_github('aiti-flinders/aurin-innovation')"

      - name: Create data
        run: |
          Rscript -e "library(aurininnovation)"
          Rscript -e "source('data-raw/regional_innovation.R')"
          Rscript -e "source('data-raw/knowledge_capability_data.R')"

      - name: Commit
        run: |
          git config --global user.name 'Hamish Gamble'
          git config --global user.email 'gamb0043@flinders.edu.au'
          git add .
          git commit -m 'Data generating functions updated' || echo 'No changes to commit'
          git push || echo 'No changes to commit'

